CREATE TABLE tbl_user(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(50)
)CHARSET=UTF8;

INSERT INTO tbl_user VALUES(DEFAULT,'张三');
INSERT INTO tbl_user VALUES(DEFAULT,'李四');
INSERT INTO tbl_user VALUES(DEFAULT,'王五');